# Generated by Django 4.2.3 on 2023-08-31 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_name', models.CharField(max_length=100)),
                ('crs_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_address', models.TextField()),
                ('t_age', models.IntegerField()),
                ('t_gender', models.CharField(max_length=100)),
                ('t_email', models.CharField(max_length=255)),
                ('t_phone', models.IntegerField()),
                ('t_image', models.ImageField(null=True, upload_to='image/')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.coursemodel')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=255)),
                ('s_address', models.TextField()),
                ('s_gender', models.CharField(max_length=100)),
                ('s_phone', models.CharField(max_length=255)),
                ('s_email', models.CharField(max_length=255)),
                ('joindate', models.DateField(auto_now_add=True)),
                ('s_image', models.ImageField(null=True, upload_to='image/')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.coursemodel')),
            ],
        ),
    ]
